image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export JAVA_HOME="/usr/lib/jvm/java-8-jdk"
  - chmod +x gradlew

variables:
  PROJECT_VERSION: "0.0.1"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  after_script:
    - "cp build/libs/*.jar ."
  artifacts:
    name: "$CI_PROJECT_NAME-$PROJECT_VERSION"
    paths:
      - "*.jar"
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

deploy:
  stage: deploy
  script:
    - ./gradlew artifactoryPublish -PartifactoryUser=$ARTIFACTORY_USER -PartifactoryPass=$ARTIFACTORY_PASS

after_script:
  - echo "End CI"
